name: image.yml
on:
  push:
  workflow_dispatch:


jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Typst
        uses: typst-community/setup-typst@v4
      
      - name: Install JetBrains Mono
        run: |
          curl -fsSL -o jbm.zip https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip
          unzip -q jbm.zip -d jbm
          mkdir -p ~/.local/share/fonts
          cp jbm/fonts/ttf/*.ttf ~/.local/share/fonts/
          fc-cache -f
          typst fonts | grep -i "JetBrains Mono"

      - name: Compile PDF
        run: |
          mkdir -p _site
          typst compile --root . exam.typ _site/exam.pdf

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        id: exam
        with:
          path: _site

  publish:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.exam.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: exam
        uses: actions/deploy-pages@v4
